# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev

  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.dayshuai.**.dto
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mysql/mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml





